print(type('123'))
print(type(int("123")))
name_of_the_user=input()
length_of_the_user=len(name_of_the_user)
print("number of the letters in your name : ",str(length_of_the_user))
print(round(length_of_the_user,2))
